export const projects = [{
  day: 1,
  name: "AI Chatbot",
  img: "https://media.giphy.com/media/1ircViuXgDKJXMlNVS/giphy.gif",
  topic: "Bits and Pieces",
  linkToCode: "https://dialogflow.com/",
  linkToDemo: "https://twitter.com/GingertonicSt/status/1061304633988169731"
},
{
  day: 2,
  name: "Floating cubes",
  img: "https://media.giphy.com/media/jIhS58Sil2FeMxpedt/giphy.gif",
  topic: "ThreeJS",
  linkToCode: "https://github.com/Gingertonic/threejs-experiments",
  linkToDemo: "https://twitter.com/GingertonicSt/status/1061729093933301760"
},
{
  day: 3,
  name: "Hello Mobile World!",
  img: "https://media.giphy.com/media/57WAdOlMWuaAK12qRP/giphy.gif",
  topic: "React Native",
  linkToCode: "https://github.com/Gingertonic/react-native-test",
  linkToDemo: "https://twitter.com/GingertonicSt/status/1062079837937025024"
},
{
  day: 4,
  name: "Hai der world",
  img: "https://pbs.twimg.com/media/Dr51oKTXgAAX-2l.jpg:large",
  topic: "Back to Multilingual Basics",
  linkToCode: "https://github.com/Gingertonic/back-to-multilingual-basics/tree/master/hello-world",
  linkToDemo: "https://twitter.com/GingertonicSt/status/1062416378039361536"
},
{
  day: 5,
  name: "Ready for Bed",
  img: "https://media.giphy.com/media/1xoGvoobsW9YXkQslt/giphy.gif",
  topic: "JS Minigames",
  linkToCode: "https://github.com/Gingertonic/js-minigames/tree/master/1_ready-for-bed",
  linkToDemo: "https://twitter.com/GingertonicSt/status/1062836008851513344"
},
{
  day: 6,
  name: "Published Writer!",
  img: "https://cdn-images-1.medium.com/max/1440/1*U-LZMuz1DisXABtocubS4g.png",
  topic: "Tech Blog",
  linkToCode: "https://medium.com/coderlist/congratulations-you-graduated-your-online-coding-course-what-now-f39d7360ba39",
  linkToDemo: "https://medium.com/coderlist/congratulations-you-graduated-your-online-coding-course-what-now-f39d7360ba39"
},
{
  day: 7,
  name: "100 Days Tracker",
  img: "https://media.giphy.com/media/21JAZQJNZvrZreUZyJ/giphy.gif",
  topic: "React App",
  linkToCode: "https://github.com/Gingertonic/one-hundred-days-of-code-tracker",
  linkToDemo: "https://one-hundred-days.herokuapp.com/"
},
{
  day: 8,
  name: "Flashy Blinkies with a Hurty Hand!",
  img: "https://pbs.twimg.com/media/DsPVcLmXoAAS-2I.jpg:large",
  topic: "Client Work",
  linkToCode: "https://github.com/Gingertonic/one-hundred-days-of-code-tracker",
  linkToDemo: "https://twitter.com/GingertonicSt/status/1063928647000707074"
},
{day: 9, name: "", img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQA8Shzc1V5b1DbaYrq6DSBjlqMLq7xUlO91HHjDV8u8OTN_3t3", topic: "", linkToCode: "", linkToDemo: ""},
{day: 10, name: "", img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQA8Shzc1V5b1DbaYrq6DSBjlqMLq7xUlO91HHjDV8u8OTN_3t3", topic: "", linkToCode: "", linkToDemo: ""},
{day: 11, name: "", img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQA8Shzc1V5b1DbaYrq6DSBjlqMLq7xUlO91HHjDV8u8OTN_3t3", topic: "", linkToCode: "", linkToDemo: ""},
{day: 12, name: "", img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQA8Shzc1V5b1DbaYrq6DSBjlqMLq7xUlO91HHjDV8u8OTN_3t3", topic: "", linkToCode: "", linkToDemo: ""},
{day: 13, name: "", img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQA8Shzc1V5b1DbaYrq6DSBjlqMLq7xUlO91HHjDV8u8OTN_3t3", topic: "", linkToCode: "", linkToDemo: ""},
{day: 14, name: "", img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQA8Shzc1V5b1DbaYrq6DSBjlqMLq7xUlO91HHjDV8u8OTN_3t3", topic: "", linkToCode: "", linkToDemo: ""},
{day: 15, name: "", img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQA8Shzc1V5b1DbaYrq6DSBjlqMLq7xUlO91HHjDV8u8OTN_3t3", topic: "", linkToCode: "", linkToDemo: ""},
{day: 16, name: "", img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQA8Shzc1V5b1DbaYrq6DSBjlqMLq7xUlO91HHjDV8u8OTN_3t3", topic: "", linkToCode: "", linkToDemo: ""},
{day: 17, name: "", img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQA8Shzc1V5b1DbaYrq6DSBjlqMLq7xUlO91HHjDV8u8OTN_3t3", topic: "", linkToCode: "", linkToDemo: ""},
{day: 18, name: "", img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQA8Shzc1V5b1DbaYrq6DSBjlqMLq7xUlO91HHjDV8u8OTN_3t3", topic: "", linkToCode: "", linkToDemo: ""},
{day: 19, name: "", img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQA8Shzc1V5b1DbaYrq6DSBjlqMLq7xUlO91HHjDV8u8OTN_3t3", topic: "", linkToCode: "", linkToDemo: ""},
{day: 20, name: "", img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQA8Shzc1V5b1DbaYrq6DSBjlqMLq7xUlO91HHjDV8u8OTN_3t3", topic: "", linkToCode: "", linkToDemo: ""},
{day: 21, name: "", img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQA8Shzc1V5b1DbaYrq6DSBjlqMLq7xUlO91HHjDV8u8OTN_3t3", topic: "", linkToCode: "", linkToDemo: ""},
{day: 22, name: "", img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQA8Shzc1V5b1DbaYrq6DSBjlqMLq7xUlO91HHjDV8u8OTN_3t3", topic: "", linkToCode: "", linkToDemo: ""},
{day: 23, name: "", img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQA8Shzc1V5b1DbaYrq6DSBjlqMLq7xUlO91HHjDV8u8OTN_3t3", topic: "", linkToCode: "", linkToDemo: ""},
{day: 24, name: "", img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQA8Shzc1V5b1DbaYrq6DSBjlqMLq7xUlO91HHjDV8u8OTN_3t3", topic: "", linkToCode: "", linkToDemo: ""},
{day: 25, name: "", img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQA8Shzc1V5b1DbaYrq6DSBjlqMLq7xUlO91HHjDV8u8OTN_3t3", topic: "", linkToCode: "", linkToDemo: ""},
{day: 26, name: "", img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQA8Shzc1V5b1DbaYrq6DSBjlqMLq7xUlO91HHjDV8u8OTN_3t3", topic: "", linkToCode: "", linkToDemo: ""},
{day: 27, name: "", img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQA8Shzc1V5b1DbaYrq6DSBjlqMLq7xUlO91HHjDV8u8OTN_3t3", topic: "", linkToCode: "", linkToDemo: ""},
{day: 28, name: "", img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQA8Shzc1V5b1DbaYrq6DSBjlqMLq7xUlO91HHjDV8u8OTN_3t3", topic: "", linkToCode: "", linkToDemo: ""},
{day: 29, name: "", img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQA8Shzc1V5b1DbaYrq6DSBjlqMLq7xUlO91HHjDV8u8OTN_3t3", topic: "", linkToCode: "", linkToDemo: ""},
{day: 30, name: "", img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQA8Shzc1V5b1DbaYrq6DSBjlqMLq7xUlO91HHjDV8u8OTN_3t3", topic: "", linkToCode: "", linkToDemo: ""},
{day: 31, name: "", img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQA8Shzc1V5b1DbaYrq6DSBjlqMLq7xUlO91HHjDV8u8OTN_3t3", topic: "", linkToCode: "", linkToDemo: ""},
{day: 32, name: "", img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQA8Shzc1V5b1DbaYrq6DSBjlqMLq7xUlO91HHjDV8u8OTN_3t3", topic: "", linkToCode: "", linkToDemo: ""},
{day: 33, name: "", img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQA8Shzc1V5b1DbaYrq6DSBjlqMLq7xUlO91HHjDV8u8OTN_3t3", topic: "", linkToCode: "", linkToDemo: ""},
{day: 34, name: "", img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQA8Shzc1V5b1DbaYrq6DSBjlqMLq7xUlO91HHjDV8u8OTN_3t3", topic: "", linkToCode: "", linkToDemo: ""},
{day: 35, name: "", img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQA8Shzc1V5b1DbaYrq6DSBjlqMLq7xUlO91HHjDV8u8OTN_3t3", topic: "", linkToCode: "", linkToDemo: ""},
{day: 36, name: "", img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQA8Shzc1V5b1DbaYrq6DSBjlqMLq7xUlO91HHjDV8u8OTN_3t3", topic: "", linkToCode: "", linkToDemo: ""},
{day: 37, name: "", img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQA8Shzc1V5b1DbaYrq6DSBjlqMLq7xUlO91HHjDV8u8OTN_3t3", topic: "", linkToCode: "", linkToDemo: ""},
{day: 38, name: "", img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQA8Shzc1V5b1DbaYrq6DSBjlqMLq7xUlO91HHjDV8u8OTN_3t3", topic: "", linkToCode: "", linkToDemo: ""},
{day: 39, name: "", img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQA8Shzc1V5b1DbaYrq6DSBjlqMLq7xUlO91HHjDV8u8OTN_3t3", topic: "", linkToCode: "", linkToDemo: ""},
{day: 40, name: "", img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQA8Shzc1V5b1DbaYrq6DSBjlqMLq7xUlO91HHjDV8u8OTN_3t3", topic: "", linkToCode: "", linkToDemo: ""},
{day: 41, name: "", img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQA8Shzc1V5b1DbaYrq6DSBjlqMLq7xUlO91HHjDV8u8OTN_3t3", topic: "", linkToCode: "", linkToDemo: ""},
{day: 42, name: "", img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQA8Shzc1V5b1DbaYrq6DSBjlqMLq7xUlO91HHjDV8u8OTN_3t3", topic: "", linkToCode: "", linkToDemo: ""},
{day: 43, name: "", img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQA8Shzc1V5b1DbaYrq6DSBjlqMLq7xUlO91HHjDV8u8OTN_3t3", topic: "", linkToCode: "", linkToDemo: ""},
{day: 44, name: "", img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQA8Shzc1V5b1DbaYrq6DSBjlqMLq7xUlO91HHjDV8u8OTN_3t3", topic: "", linkToCode: "", linkToDemo: ""},
{day: 45, name: "", img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQA8Shzc1V5b1DbaYrq6DSBjlqMLq7xUlO91HHjDV8u8OTN_3t3", topic: "", linkToCode: "", linkToDemo: ""},
{day: 46, name: "", img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQA8Shzc1V5b1DbaYrq6DSBjlqMLq7xUlO91HHjDV8u8OTN_3t3", topic: "", linkToCode: "", linkToDemo: ""},
{day: 47, name: "", img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQA8Shzc1V5b1DbaYrq6DSBjlqMLq7xUlO91HHjDV8u8OTN_3t3", topic: "", linkToCode: "", linkToDemo: ""},
{day: 48, name: "", img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQA8Shzc1V5b1DbaYrq6DSBjlqMLq7xUlO91HHjDV8u8OTN_3t3", topic: "", linkToCode: "", linkToDemo: ""},
{day: 49, name: "", img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQA8Shzc1V5b1DbaYrq6DSBjlqMLq7xUlO91HHjDV8u8OTN_3t3", topic: "", linkToCode: "", linkToDemo: ""},
{day: 50, name: "", img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQA8Shzc1V5b1DbaYrq6DSBjlqMLq7xUlO91HHjDV8u8OTN_3t3", topic: "", linkToCode: "", linkToDemo: ""},
{day: 51, name: "", img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQA8Shzc1V5b1DbaYrq6DSBjlqMLq7xUlO91HHjDV8u8OTN_3t3", topic: "", linkToCode: "", linkToDemo: ""},
{day: 52, name: "", img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQA8Shzc1V5b1DbaYrq6DSBjlqMLq7xUlO91HHjDV8u8OTN_3t3", topic: "", linkToCode: "", linkToDemo: ""},
{day: 53, name: "", img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQA8Shzc1V5b1DbaYrq6DSBjlqMLq7xUlO91HHjDV8u8OTN_3t3", topic: "", linkToCode: "", linkToDemo: ""},
{day: 54, name: "", img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQA8Shzc1V5b1DbaYrq6DSBjlqMLq7xUlO91HHjDV8u8OTN_3t3", topic: "", linkToCode: "", linkToDemo: ""},
{day: 55, name: "", img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQA8Shzc1V5b1DbaYrq6DSBjlqMLq7xUlO91HHjDV8u8OTN_3t3", topic: "", linkToCode: "", linkToDemo: ""},
{day: 56, name: "", img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQA8Shzc1V5b1DbaYrq6DSBjlqMLq7xUlO91HHjDV8u8OTN_3t3", topic: "", linkToCode: "", linkToDemo: ""},
{day: 57, name: "", img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQA8Shzc1V5b1DbaYrq6DSBjlqMLq7xUlO91HHjDV8u8OTN_3t3", topic: "", linkToCode: "", linkToDemo: ""},
{day: 58, name: "", img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQA8Shzc1V5b1DbaYrq6DSBjlqMLq7xUlO91HHjDV8u8OTN_3t3", topic: "", linkToCode: "", linkToDemo: ""},
{day: 59, name: "", img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQA8Shzc1V5b1DbaYrq6DSBjlqMLq7xUlO91HHjDV8u8OTN_3t3", topic: "", linkToCode: "", linkToDemo: ""},
{day: 60, name: "", img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQA8Shzc1V5b1DbaYrq6DSBjlqMLq7xUlO91HHjDV8u8OTN_3t3", topic: "", linkToCode: "", linkToDemo: ""},
{day: 61, name: "", img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQA8Shzc1V5b1DbaYrq6DSBjlqMLq7xUlO91HHjDV8u8OTN_3t3", topic: "", linkToCode: "", linkToDemo: ""},
{day: 62, name: "", img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQA8Shzc1V5b1DbaYrq6DSBjlqMLq7xUlO91HHjDV8u8OTN_3t3", topic: "", linkToCode: "", linkToDemo: ""},
{day: 63, name: "", img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQA8Shzc1V5b1DbaYrq6DSBjlqMLq7xUlO91HHjDV8u8OTN_3t3", topic: "", linkToCode: "", linkToDemo: ""},
{day: 64, name: "", img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQA8Shzc1V5b1DbaYrq6DSBjlqMLq7xUlO91HHjDV8u8OTN_3t3", topic: "", linkToCode: "", linkToDemo: ""},
{day: 65, name: "", img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQA8Shzc1V5b1DbaYrq6DSBjlqMLq7xUlO91HHjDV8u8OTN_3t3", topic: "", linkToCode: "", linkToDemo: ""},
{day: 66, name: "", img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQA8Shzc1V5b1DbaYrq6DSBjlqMLq7xUlO91HHjDV8u8OTN_3t3", topic: "", linkToCode: "", linkToDemo: ""},
{day: 67, name: "", img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQA8Shzc1V5b1DbaYrq6DSBjlqMLq7xUlO91HHjDV8u8OTN_3t3", topic: "", linkToCode: "", linkToDemo: ""},
{day: 68, name: "", img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQA8Shzc1V5b1DbaYrq6DSBjlqMLq7xUlO91HHjDV8u8OTN_3t3", topic: "", linkToCode: "", linkToDemo: ""},
{day: 69, name: "", img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQA8Shzc1V5b1DbaYrq6DSBjlqMLq7xUlO91HHjDV8u8OTN_3t3", topic: "", linkToCode: "", linkToDemo: ""},
{day: 70, name: "", img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQA8Shzc1V5b1DbaYrq6DSBjlqMLq7xUlO91HHjDV8u8OTN_3t3", topic: "", linkToCode: "", linkToDemo: ""},
{day: 71, name: "", img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQA8Shzc1V5b1DbaYrq6DSBjlqMLq7xUlO91HHjDV8u8OTN_3t3", topic: "", linkToCode: "", linkToDemo: ""},
{day: 72, name: "", img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQA8Shzc1V5b1DbaYrq6DSBjlqMLq7xUlO91HHjDV8u8OTN_3t3", topic: "", linkToCode: "", linkToDemo: ""},
{day: 73, name: "", img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQA8Shzc1V5b1DbaYrq6DSBjlqMLq7xUlO91HHjDV8u8OTN_3t3", topic: "", linkToCode: "", linkToDemo: ""},
{day: 74, name: "", img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQA8Shzc1V5b1DbaYrq6DSBjlqMLq7xUlO91HHjDV8u8OTN_3t3", topic: "", linkToCode: "", linkToDemo: ""},
{day: 75, name: "", img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQA8Shzc1V5b1DbaYrq6DSBjlqMLq7xUlO91HHjDV8u8OTN_3t3", topic: "", linkToCode: "", linkToDemo: ""},
{day: 76, name: "", img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQA8Shzc1V5b1DbaYrq6DSBjlqMLq7xUlO91HHjDV8u8OTN_3t3", topic: "", linkToCode: "", linkToDemo: ""},
{day: 77, name: "", img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQA8Shzc1V5b1DbaYrq6DSBjlqMLq7xUlO91HHjDV8u8OTN_3t3", topic: "", linkToCode: "", linkToDemo: ""},
{day: 78, name: "", img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQA8Shzc1V5b1DbaYrq6DSBjlqMLq7xUlO91HHjDV8u8OTN_3t3", topic: "", linkToCode: "", linkToDemo: ""},
{day: 79, name: "", img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQA8Shzc1V5b1DbaYrq6DSBjlqMLq7xUlO91HHjDV8u8OTN_3t3", topic: "", linkToCode: "", linkToDemo: ""},
{day: 80, name: "", img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQA8Shzc1V5b1DbaYrq6DSBjlqMLq7xUlO91HHjDV8u8OTN_3t3", topic: "", linkToCode: "", linkToDemo: ""},
{day: 81, name: "", img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQA8Shzc1V5b1DbaYrq6DSBjlqMLq7xUlO91HHjDV8u8OTN_3t3", topic: "", linkToCode: "", linkToDemo: ""},
{day: 82, name: "", img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQA8Shzc1V5b1DbaYrq6DSBjlqMLq7xUlO91HHjDV8u8OTN_3t3", topic: "", linkToCode: "", linkToDemo: ""},
{day: 83, name: "", img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQA8Shzc1V5b1DbaYrq6DSBjlqMLq7xUlO91HHjDV8u8OTN_3t3", topic: "", linkToCode: "", linkToDemo: ""},
{day: 84, name: "", img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQA8Shzc1V5b1DbaYrq6DSBjlqMLq7xUlO91HHjDV8u8OTN_3t3", topic: "", linkToCode: "", linkToDemo: ""},
{day: 85, name: "", img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQA8Shzc1V5b1DbaYrq6DSBjlqMLq7xUlO91HHjDV8u8OTN_3t3", topic: "", linkToCode: "", linkToDemo: ""},
{day: 86, name: "", img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQA8Shzc1V5b1DbaYrq6DSBjlqMLq7xUlO91HHjDV8u8OTN_3t3", topic: "", linkToCode: "", linkToDemo: ""},
{day: 87, name: "", img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQA8Shzc1V5b1DbaYrq6DSBjlqMLq7xUlO91HHjDV8u8OTN_3t3", topic: "", linkToCode: "", linkToDemo: ""},
{day: 88, name: "", img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQA8Shzc1V5b1DbaYrq6DSBjlqMLq7xUlO91HHjDV8u8OTN_3t3", topic: "", linkToCode: "", linkToDemo: ""},
{day: 89, name: "", img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQA8Shzc1V5b1DbaYrq6DSBjlqMLq7xUlO91HHjDV8u8OTN_3t3", topic: "", linkToCode: "", linkToDemo: ""},
{day: 90, name: "", img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQA8Shzc1V5b1DbaYrq6DSBjlqMLq7xUlO91HHjDV8u8OTN_3t3", topic: "", linkToCode: "", linkToDemo: ""},
{day: 91, name: "", img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQA8Shzc1V5b1DbaYrq6DSBjlqMLq7xUlO91HHjDV8u8OTN_3t3", topic: "", linkToCode: "", linkToDemo: ""},
{day: 92, name: "", img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQA8Shzc1V5b1DbaYrq6DSBjlqMLq7xUlO91HHjDV8u8OTN_3t3", topic: "", linkToCode: "", linkToDemo: ""},
{day: 93, name: "", img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQA8Shzc1V5b1DbaYrq6DSBjlqMLq7xUlO91HHjDV8u8OTN_3t3", topic: "", linkToCode: "", linkToDemo: ""},
{day: 94, name: "", img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQA8Shzc1V5b1DbaYrq6DSBjlqMLq7xUlO91HHjDV8u8OTN_3t3", topic: "", linkToCode: "", linkToDemo: ""},
{day: 95, name: "", img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQA8Shzc1V5b1DbaYrq6DSBjlqMLq7xUlO91HHjDV8u8OTN_3t3", topic: "", linkToCode: "", linkToDemo: ""},
{day: 96, name: "", img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQA8Shzc1V5b1DbaYrq6DSBjlqMLq7xUlO91HHjDV8u8OTN_3t3", topic: "", linkToCode: "", linkToDemo: ""},
{day: 97, name: "", img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQA8Shzc1V5b1DbaYrq6DSBjlqMLq7xUlO91HHjDV8u8OTN_3t3", topic: "", linkToCode: "", linkToDemo: ""},
{day: 98, name: "", img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQA8Shzc1V5b1DbaYrq6DSBjlqMLq7xUlO91HHjDV8u8OTN_3t3", topic: "", linkToCode: "", linkToDemo: ""},
{day: 99, name: "", img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQA8Shzc1V5b1DbaYrq6DSBjlqMLq7xUlO91HHjDV8u8OTN_3t3", topic: "", linkToCode: "", linkToDemo: ""},
{day: 100, name: "", img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQA8Shzc1V5b1DbaYrq6DSBjlqMLq7xUlO91HHjDV8u8OTN_3t3", topic: "", linkToCode: "", linkToDemo: ""}
]
